### PR TITLE
Simply call the functions

### LINKED ISSUE #3: Failed to activate the single-click-open package
Started with Atom 1.12.0-beta0
Opening any document generates this error.

**Atom Version**: 1.12.0-beta0
**Electron Version**: 1.3.6
**System**: Mac OS X 10.11.6
**Thrown From**: [single-click-open](https://github.com/olmokramer/atom-single-click-open) package, v0.2.1
### Stack Trace

Failed to activate the single-click-open package

```
At Arguments to CompositeDisposable.add must have a .dispose() method

TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:70:13)
    at CompositeDisposable.module.exports.CompositeDisposable.add (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:43:11)
    at Object.activate (/Users/bmiller/.atom/packages/single-click-open/lib/single-click-open.js:28:17)
    at Package.module.exports.Package.activateNow (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:184:19)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:157:32
    at Package.module.exports.Package.measure (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:150:26
    at Package.module.exports.Package.activate (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:147:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package-manager.js:548:21)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/package-manager.js:529:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package-manager.js:524:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package-manager.js:506:46)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/atom-environment.js:783:28
```
###

### PR DESCRIPTION
**Pull request by bjmiller**
Don't pass the return values of the functions to `CompositeDisposable.add`.

It was probably never the correct behavior, and now the interface assertions are returning an error.  I believe that this fixes #3.

### CODE REVIEW

File: lib/single-click-open.js [hunk 1]
```diff
@@ -25,10 +25,10 @@ export function activate() {
...
   if (atom.config.get('single-click-open.fixTreeView'))
-    disposables.add(disablePendingItems());
+    disablePendingItems();
 
   if (atom.config.get('single-click-open.fixSearchResultsView'))
-    disposables.add(disableSearchResultDoubleClick());
+    disableSearchResultDoubleClick();
 }
 
 export function deactivate() {
```
Comment (iam4x) [inline lib/single-click-open.js:34]: in `deactivate()` it calls `disposable.dispose()` and it should be `disposables`

Comment (bjmiller) [reply lib/single-click-open.js:34]: Good catch.  I don't think that was actually breaking anything, but it can't hurt to get it right.

**Comment by bjmiller** [comment]
@olmokramer: It would be awesome if you could approve & publish this today.  Let me know if any changes are needed.

**Comment by jmsdnns** [comment]
+1

**Comment by panuhorsmalahti** [comment]
+1

**Comment by bronson** [comment]
Yes, this is an important fix!

**Comment by MiracleBlue** [comment]
Hey folks, @olmokramer very kindly gave me contributor status to assist in his absence, so I'm gonna merge this and try publish it now, and hopefully it will all work just like that :) here goes!
